# Generated by Django 5.0.6 on 2024-07-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=50, unique=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="member_rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "requestMember",
                    models.ManyToManyField(
                        related_name="rooms_requested", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "room_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
