# Generated by Django 5.0.6 on 2024-07-21 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="requestMember",
            new_name="request_member",
        ),
    ]
