# Generated by Django 5.0.6 on 2024-07-21 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_rename_requestmember_room_request_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="request_member",
            new_name="request_members",
        ),
    ]
