# Generated by Django 5.0.6 on 2024-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_request_member_room_request_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
