# Generated by Django 5.0.6 on 2024-07-22 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="rooms_owner",
        ),
    ]
