# Generated by Django 5.0.6 on 2024-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_customuser_rooms_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
