# Generated by Django 5.0.6 on 2024-07-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notifications',
        ),
    ]
